# This is the network config written by 'subiquity'
network:
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false
      addresses:
          - 192.168.64.9/30
    eth1:
      dhcp4: true
      optional: true
    eth2:
      dhcp4: false
      dhcp6: false
      accept-ra: false
      link-local: []
      addresses:
          - 10.0.0.1/24
    eth3:
      dhcp4: true
      optional: true
      dhcp4-overrides:
        route-metric: 200
  version: 2